//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ART {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Art {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Art() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ART.Art", typeof(Art).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked.
        /// </summary>
        public static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of attempts allowed, your account has been locked for.
        /// </summary>
        public static string AccountLockMsg {
            get {
                return ResourceManager.GetString("AccountLockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not locked.
        /// </summary>
        public static string AccountNotLocked {
            get {
                return ResourceManager.GetString("AccountNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Recovery Tool.
        /// </summary>
        public static string AccountRecoveryTool {
            get {
                return ResourceManager.GetString("AccountRecoveryTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        public static string accountunlock_home {
            get {
                return ResourceManager.GetString("accountunlock_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the questions must be answered.
        /// </summary>
        public static string AllQuestionAnswerMandateError {
            get {
                return ResourceManager.GetString("AllQuestionAnswerMandateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer is wrong, please try again.
        /// </summary>
        public static string AnswerWrongErrMsg {
            get {
                return ResourceManager.GetString("AnswerWrongErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meta data goes here....
        /// </summary>
        public static string ArtCaption {
            get {
                return ResourceManager.GetString("ArtCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017 Hexaware Technologies. All rights reserved..
        /// </summary>
        public static string ArtCopyRights {
            get {
                return ResourceManager.GetString("ArtCopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Type.
        /// </summary>
        public static string AuthenticationType {
            get {
                return ResourceManager.GetString("AuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change/OTP Password.
        /// </summary>
        public static string ChangeOTPPassword {
            get {
                return ResourceManager.GetString("ChangeOTPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change / otp password.
        /// </summary>
        public static string changeotppassword_home {
            get {
                return ResourceManager.GetString("changeotppassword_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to accept the changes please fill in the information below.
        /// </summary>
        public static string ChangepasswordCaption {
            get {
                return ResourceManager.GetString("ChangepasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to unlock.
        /// </summary>
        public static string ClickHereToUnlock {
            get {
                return ResourceManager.GetString("ClickHereToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly confirm your answer. To proceed please click &quot;Submit&quot; else  &quot;Cancel&quot;..
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password must have minimum 6 characters.
        /// </summary>
        public static string CurPassMin6Char {
            get {
                return ResourceManager.GetString("CurPassMin6Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a user session available in the browser, Please close and login with a different user.
        /// </summary>
        public static string DiffSessionMsg {
            get {
                return ResourceManager.GetString("DiffSessionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the answer.
        /// </summary>
        public static string EmptyAnswerwError {
            get {
                return ResourceManager.GetString("EmptyAnswerwError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering for the OTP facility allows you to use your mobile number for the authentication process. Use the OTP option if you forget your password and need to unlock your account..
        /// </summary>
        public static string EnableOTP_Caption {
            get {
                return ResourceManager.GetString("EnableOTP_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        public static string Enter_OTP {
            get {
                return ResourceManager.GetString("Enter_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the captcha shown below (case sensitive).
        /// </summary>
        public static string EnterCaptchaImageText {
            get {
                return ResourceManager.GetString("EnterCaptchaImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        public static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your date of birth.
        /// </summary>
        public static string EnterDOB {
            get {
                return ResourceManager.GetString("EnterDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your mobile number.
        /// </summary>
        public static string EnterMobileNumber {
            get {
                return ResourceManager.GetString("EnterMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the received OTP.
        /// </summary>
        public static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the received OTP.
        /// </summary>
        public static string EnterReceivedOtp {
            get {
                return ResourceManager.GetString("EnterReceivedOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User ID.
        /// </summary>
        public static string EnterUserId {
            get {
                return ResourceManager.GetString("EnterUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User ID.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your User ID.
        /// </summary>
        public static string EnterYourUserId {
            get {
                return ResourceManager.GetString("EnterYourUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your User Name.
        /// </summary>
        public static string EnterYourUserName {
            get {
                return ResourceManager.GetString("EnterYourUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for might have been moved, its name changed or temporarily unvailable.
        /// </summary>
        public static string Error404Msg {
            get {
                return ResourceManager.GetString("Error404Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again after sometime.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending the message.
        /// </summary>
        public static string ErrorSendMsg {
            get {
                return ResourceManager.GetString("ErrorSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are not authenticated to access this site, please contact administrator.
        /// </summary>
        public static string ExcemptedUserMsg {
            get {
                return ResourceManager.GetString("ExcemptedUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great.
        /// </summary>
        public static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &lt;br/&gt;
        ///Password.
        /// </summary>
        public static string HomeChangePassword {
            get {
                return ResourceManager.GetString("HomeChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &lt;br/&gt;
        ///Password.
        /// </summary>
        public static string HomeResetPassword {
            get {
                return ResourceManager.GetString("HomeResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock &lt;br/&gt;
        ///Account.
        /// </summary>
        public static string HomeUnlockAccount {
            get {
                return ResourceManager.GetString("HomeUnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Enroll&amp;nbsp;/&lt;br/&gt;
        ///Update.
        /// </summary>
        public static string HomeUserEnroll {
            get {
                return ResourceManager.GetString("HomeUserEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth format is incorrect.
        /// </summary>
        public static string IncorrectDOBFormat {
            get {
                return ResourceManager.GetString("IncorrectDOBFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Captcha.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        public static string InvalidDOB {
            get {
                return ResourceManager.GetString("InvalidDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name / Password.
        /// </summary>
        public static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of 13 characters only.
        /// </summary>
        public static string Max13Char {
            get {
                return ResourceManager.GetString("Max13Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum of 6 characters.
        /// </summary>
        public static string Min6Char {
            get {
                return ResourceManager.GetString("Min6Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum of 9 characters.
        /// </summary>
        public static string Min9Char {
            get {
                return ResourceManager.GetString("Min9Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters between 9-13 only.
        /// </summary>
        public static string MinMaxMsg {
            get {
                return ResourceManager.GetString("MinMaxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User ID.
        /// </summary>
        public static string MissingUserID {
            get {
                return ResourceManager.GetString("MissingUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make my mobile number private.
        /// </summary>
        public static string MobileNumberIsPrivate {
            get {
                return ResourceManager.GetString("MobileNumberIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your mobile number.
        /// </summary>
        public static string MobileNumberToolTip {
            get {
                return ResourceManager.GetString("MobileNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while update mobile number, please try after sometime.
        /// </summary>
        public static string MobileNumRegisterFailure {
            get {
                return ResourceManager.GetString("MobileNumRegisterFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mobile number updated successfully!!!, please click on Next to continue.
        /// </summary>
        public static string MobileNumRegisterSuccess {
            get {
                return ResourceManager.GetString("MobileNumRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mobile number is not validated yet, click &quot;Ok&quot; to continue the validation or &quot;Cancel&quot; to skip the mobile number registeration.
        /// </summary>
        public static string MobilNumberRegisterValidation {
            get {
                return ResourceManager.GetString("MobilNumberRegisterValidation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your mobile number is not validated yet, click &quot;Ok&quot; to continue the validation or &quot;Cancel&quot; to skip the mobile number registeration.
        /// </summary>
        public static string USMobilNumberRegisterValidation
        {
            get
            {
                return ResourceManager.GetString("USMobilNumberRegisterValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One numeric character.
        /// </summary>
        public static string OneNumericChar {
            get {
                return ResourceManager.GetString("OneNumericChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One small letter.
        /// </summary>
        public static string OneSmallLetter {
            get {
                return ResourceManager.GetString("OneSmallLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One special character.
        /// </summary>
        public static string OneSpecialChar {
            get {
                return ResourceManager.GetString("OneSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One uppercase letter.
        /// </summary>
        public static string OneUpperCaseLetter {
            get {
                return ResourceManager.GetString("OneUpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP will be sent to.
        /// </summary>
        public static string OTP_Caption {
            get {
                return ResourceManager.GetString("OTP_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable this feature, please enroll again with  &quot;Register for OTP&quot; option.
        /// </summary>
        public static string OTPDisableMsg {
            get {
                return ResourceManager.GetString("OTPDisableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to network issues, you might not have received the OTP. Pls try with .
        /// </summary>
        public static string OTPFailureMsg {
            get {
                return ResourceManager.GetString("OTPFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum number of attempts, please try after sometime.
        /// </summary>
        public static string OTPMaxAttemptMsg {
            get {
                return ResourceManager.GetString("OTPMaxAttemptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP must have a minimum of 6 characters.
        /// </summary>
        public static string OTPMin6Char {
            get {
                return ResourceManager.GetString("OTPMin6Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP should be minimum of 6 characters.
        /// </summary>
        public static string OTPMinMsg {
            get {
                return ResourceManager.GetString("OTPMinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would receive your OTP in.
        /// </summary>
        public static string OTPReceiveMsg {
            get {
                return ResourceManager.GetString("OTPReceiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still you didn&apos;t receive the OTP? please.
        /// </summary>
        public static string OTPResendMsg {
            get {
                return ResourceManager.GetString("OTPResendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password matches your password history or not allowed to change in 24 hours.
        /// </summary>
        public static string PasswordHistoryErrMsg {
            get {
                return ResourceManager.GetString("PasswordHistoryErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string PasswordInfo_information {
            get {
                return ResourceManager.GetString("PasswordInfo_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 9 characters and Maximum 13 characters long.
        /// </summary>
        public static string PasswordInfo_information1 {
            get {
                return ResourceManager.GetString("PasswordInfo_information1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 13 characters in length.
        /// </summary>
        public static string PasswordInfo_information2 {
            get {
                return ResourceManager.GetString("PasswordInfo_information2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should have at least any four of the below - 
        ///•One capital letter
        ///•One small letter
        ///•One numeric
        ///•One special character 
        ///(Except -`:&quot;[]&apos;).
        /// </summary>
        public static string PasswordInfo_information3 {
            get {
                return ResourceManager.GetString("PasswordInfo_information3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not have been used last 7 times..
        /// </summary>
        public static string PasswordInfo_information4 {
            get {
                return ResourceManager.GetString("PasswordInfo_information4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not contain your employee id or the phrase password, pass , hexaware ,hex etc....
        /// </summary>
        public static string PasswordInfo_information5 {
            get {
                return ResourceManager.GetString("PasswordInfo_information5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordInfo_information6 {
            get {
                return ResourceManager.GetString("PasswordInfo_information6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Should be 9-13 Characters long.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least one small letter, one capital letter, one symbol and one numeric character.
        /// </summary>
        public static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was successfully reset!.
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain space.
        /// </summary>
        public static string PasswordSpaceMsg {
            get {
                return ResourceManager.GetString("PasswordSpaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the captcha.
        /// </summary>
        public static string PleaseEnterImageText {
            get {
                return ResourceManager.GetString("PleaseEnterImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password.
        /// </summary>
        public static string PlsConfirmNewPassword {
            get {
                return ResourceManager.GetString("PlsConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string PlsConfirmPassword {
            get {
                return ResourceManager.GetString("PlsConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the captcha (case sensitive).
        /// </summary>
        public static string PlsEnterCaptcha {
            get {
                return ResourceManager.GetString("PlsEnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter OTP.
        /// </summary>
        public static string PlsEnterOtp {
            get {
                return ResourceManager.GetString("PlsEnterOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your question and answer is wrong.
        /// </summary>
        public static string QuestionAnswerWrong {
            get {
                return ResourceManager.GetString("QuestionAnswerWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password.
        /// </summary>
        public static string ReenterPassword {
            get {
                return ResourceManager.GetString("ReenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while registering, please try after some time!.
        /// </summary>
        public static string RegisterFailure {
            get {
                return ResourceManager.GetString("RegisterFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for OTP.
        /// </summary>
        public static string RegisterForOTP {
            get {
                return ResourceManager.GetString("RegisterForOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question and answers saved successfully!.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string resetpasswrod_home {
            get {
                return ResourceManager.GetString("resetpasswrod_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password and new password should not be same.
        /// </summary>
        public static string SamePasswordMsg {
            get {
                return ResourceManager.GetString("SamePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will navigate you to the questions page.
        /// </summary>
        public static string SecQue_Caption {
            get {
                return ResourceManager.GetString("SecQue_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        public static string SecurityQuestion {
            get {
                return ResourceManager.GetString("SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP.
        /// </summary>
        public static string SendOTP {
            get {
                return ResourceManager.GetString("SendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try after some time.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question must be unique.
        /// </summary>
        public static string UniqueQuestionValidation {
            get {
                return ResourceManager.GetString("UniqueQuestionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock.
        /// </summary>
        public static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        public static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string similar to A problem was faced while unlocking your account, please try after some time.
        /// </summary>
        public static string UnlockFailure {
            get {
                return ResourceManager.GetString("UnlockFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account was unlocked successfully!.
        /// </summary>
        public static string UnlockSuccess {
            get {
                return ResourceManager.GetString("UnlockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Enroll / Update.
        /// </summary>
        public static string userenrollupdate_home {
            get {
                return ResourceManager.GetString("userenrollupdate_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID does not exist.
        /// </summary>
        public static string UserIdNotExist {
            get {
                return ResourceManager.GetString("UserIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID does not exist.
        /// </summary>
        public static string UserNameNotExist {
            get {
                return ResourceManager.GetString("UserNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enroll to continue.
        /// </summary>
        public static string UserNotRegistered {
            get {
                return ResourceManager.GetString("UserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer the question.
        /// </summary>
        public static string ValidateAnswer {
            get {
                return ResourceManager.GetString("ValidateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate OTP.
        /// </summary>
        public static string ValidateOTP {
            get {
                return ResourceManager.GetString("ValidateOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string WizAuthentication {
            get {
                return ResourceManager.GetString("WizAuthentication", resourceCulture);
            }
        }
    }
}
