//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtMaster {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Art {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Art() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtMaster.Art", typeof(Art).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017 Hexaware Technologies. All rights reserved..
        /// </summary>
        public static string ArtCopyRights {
            get {
                return ResourceManager.GetString("ArtCopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User ID.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your User ID.
        /// </summary>
        public static string EnterYourUserId {
            get {
                return ResourceManager.GetString("EnterYourUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string WizAuthentication {
            get {
                return ResourceManager.GetString("WizAuthentication", resourceCulture);
            }
        }
        /// <summary>
        ///   To get the Error Message
        /// </summary>
        public static string Error404Msg
        {
            get
            {
                return ResourceManager.GetString("Error404Msg", resourceCulture);
            }
        }
        /// <summary>
        ///   To get the Error Message
        /// </summary>
        public static string ErrorMsg
        {
            get
            {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        public static string MobileNumberToolTip
        {
            get
            {
                return ResourceManager.GetString("MobileNumberToolTip", resourceCulture);
            }
        }
        public static string MobileNumber
        {
            get
            {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        public static string SendOTP
        {
            get
            {
                return ResourceManager.GetString("SendOTP", resourceCulture);
            }
        }
        public static string Enter_OTP
        {
            get
            {
                return ResourceManager.GetString("Enter_OTP", resourceCulture);
            }
        }
        public static string EnterReceivedOtp
        {
            get
            {
                return ResourceManager.GetString("EnterReceivedOtp", resourceCulture);
            }
        }
        public static string ValidateOTP
        {
            get
            {
                return ResourceManager.GetString("ValidateOTP", resourceCulture);
            }
        }
        public static string OTPReceiveMsg
        {
            get
            {
                return ResourceManager.GetString("OTPReceiveMsg", resourceCulture);
            }
        }
        public static string Resend
        {
            get
            {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        public static string EmployeeVerification
        {
            get
            {
                return ResourceManager.GetString("EmployeeVerification", resourceCulture);
            }
        }
        public static string MobileNumRegisterSuccess
        {
            get
            {
                return ResourceManager.GetString("MobileNumRegisterSuccess", resourceCulture);
            }
        }
        public static string MobileNumRegisterFailure
        {
            get
            {
                return ResourceManager.GetString("MobileNumRegisterFailure", resourceCulture);
            }
        }
        public static string InvalidOTP
        {
            get
            {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        public static string ErrorSendMsg
        {
            get
            {
                return ResourceManager.GetString("ErrorSendMsg", resourceCulture);
            }
        }
        public static string EnterMobileNumber
        {
            get
            {
                return ResourceManager.GetString("EnterMobileNumber", resourceCulture);
            }
        }
        public static string InvalidMobileNumber
        {
            get
            {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        public static string OTPResendMsg
        {
            get
            {
                return ResourceManager.GetString("OTPResendMsg", resourceCulture);
            }
        }
        public static string OTPMinMsg
        {
            get
            {
                return ResourceManager.GetString("OTPMinMsg", resourceCulture);
            }
        }
        public static string PlsEnterOtp
        {
            get
            {
                return ResourceManager.GetString("PlsEnterOtp", resourceCulture);
            }
        }

        public static string OTPMaxAttemptMsg
        {
            get
            {
                return ResourceManager.GetString("OTPMaxAttemptMsg", resourceCulture);
            }
        }
        public static string MobilNumberRegisterValidation
        {
            get
            {
                return ResourceManager.GetString("MobilNumberRegisterValidation", resourceCulture);
            }
        }
  

    }
}
